### ISSUE TITLE
Ajouter une date dans la route api/commune-summary pour connaitre la date de dernière modification

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-plateforme#11]
Afin de pouvoir déterminer si une commune a connu des changements et si oui depuis quand.

**Comment by jdesboeufs** [comment]
J'ai ajouté un attribut qui dit quand les données de la commune ont été assemblées la dernière fois (`composedAt`).
https://github.com/BaseAdresseNationale/ban-plateforme/commit/37ece7d57475f68e2d6aa21f1d82b2ff0270b548

C'est pas forcément ce qu'on veut mais ça pourra aider.
