### ISSUE TITLE
les lieux dits qui ont le même libellé qu'une voie, ne remontent pas dans la BAN

### ISSUE THREAD

**Issue by fufeck** [BaseAdresseNationale/ban-plateforme#111]
## Context

Les toponymes avec parcelle(s) associée(s) ne remontent pas dans la BAN.

Exemple avec le toponyme `La Gouisserie` présent dans le csv de l'api-depot et non dans le csv de l'api-ban :

Les parcelles des toponymes sont bien présentent sur la route /communes/:codeCommune/current-revision/files/bal/download de l'api-depot
[bal-50393 (1).csv](https://github.com/BaseAdresseNationale/mes-adresses/files/11135816/bal-50393.1.csv)

Les toponymes avec parcelles ne sont plus présents sur la route /ban/communes/${codeCommune}/download/csv-bal/adresses de ban_api
[adresses-50393.csv](https://github.com/BaseAdresseNationale/mes-adresses/files/11135817/adresses-50393.csv)

## Relation issue 
https://github.com/BaseAdresseNationale/mes-adresses/issues/622

**Comment by antoineludeau** [comment]
Investigation : dans le CSV BAL fourni, il y a des noms similaires pour des voies et des lieux-dits (exemple: "La Gouisserie"). Le code va donc créer une voie "La Gouisserie" et un lieu-dit "La Gouisserie". Le problème c'est que l'ID de cette voie et de ce lieu-dit vont être générés à partir d'un pseudo-code (car par de correspondance avec le code fantoir pour la voie) qui utilise en entrée : le nom (en l'occurence le même pour la voie et le lieu-dit : "La Gouisserie") et le codeAncienneCommune (ici encore le même : "50393"). L'ID généré pour les deux est : "50393_2qh69y". Il y a ensuite un filtrage qui est opéré sur les lieux-dits pour retirer ceux qui auraient le même ID qu'une voie. Ici c'est bien le cas et donc le lieu-dit "La Gouisserie" est retiré.

**Comment by antoineludeau** [comment]
Peut-on clore cette issue ?

**Comment by mmortier** [comment]
Je pense qu'il faut revoir la gestion des toponymes, des lieux dits et des voies pour résoudre ce problème.
Je reporte au prochain sprint. Les règles de gestions doivent faire l'objet d'un atelier équipe BAN - BAL

**Comment by fufeck** [comment]
Issue relié https://github.com/BaseAdresseNationale/mes-adresses/issues/704

**Comment by mmortier** [comment]
Ici le problème vient du fait qu'il existe une voie et un lieu dit avec le même libellé et que le pseudo code est calculé à partir du libellé. Ils ont le même pseudo code et le lieu dit est filtré dans la BAN.
-> je renomme l'issue de : "Les toponymes avec parcelles associées ne remontent pas dans la BAN"
-> à  : "les lieux dits qui ont le même libellé qu'une voie, ne remontent pas dans la BAN"
Pour résoudre ce problème il faut repenser la façon de gérer les voies et les LD

**Comment by mmortier** [comment]
@fufeck je ne suis pas certaine que le ticket mentionné https://github.com/BaseAdresseNationale/mes-adresses/issues/704 corresponde à la problématique. 

En tous les cas, le problème de ce ticket ne devrait plus exister lorsqu'on passera à une intégration des données avec le banId. 
Le lieu dit et la voie auront des identifiants différents. Ils remonteront donc tous les deux dans la BAN.
