### ISSUE TITLE
ajouter une route permettant d'extraire les données d'une commune

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-plateforme#12]
dans l'API de consultation BAN.
A voir pour faire la route qui donne les résultats en json ET? en CSV?

**Comment by jdesboeufs** [comment]
Nous avons déjà une route permettant d'extraire les données d'une commune au format CSV historique :
https://plateforme.adresse.data.gouv.fr/ban/communes/27115/download/csv-legacy/adresses
https://plateforme.adresse.data.gouv.fr/ban/communes/27115/download/csv-legacy/lieux-dits
