### ISSUE TITLE
ID-Fix : Implémenter une fonction de contrôle du format BanID

### ISSUE THREAD

**Issue by nkokla** [BaseAdresseNationale/ban-plateforme#130]

**Comment by mmortier** [comment]
Débloqué suite à la concertation l'Uuid v4 est retenu : https://osmose.numerique.gouv.fr/jcms/209046265_SocialTopic/fr/forme-de-l-identifiant-unique-ban-uuid-v4-vs-nano-id

**Comment by mmortier** [comment]
https://github.com/BaseAdresseNationale/id-fix/pull/17
