### ISSUE TITLE
désynchronisation BAN / BAL sur  Grand Belfort 

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-plateforme#172]
a BAL est à jour d'une nouvelle version depuis le 5 mai, or c'est une ancienne BAL qui reste dans la BAN. 
Organisation certifiée + mot clé bien présent et BAL qui passe au validateur. 
Dans data.gouv.fr : [https://www.data.gouv.fr/fr/datasets/bal-base-adresses-locale-du-grand-belfort-servant-de-reference-pour-la-ban-base-adresses-nationale-v-1-3/#/[…]s](https://www.data.gouv.fr/fr/datasets/bal-base-adresses-locale-du-grand-belfort-servant-de-reference-pour-la-ban-base-adresses-nationale-v-1-3/#/[%E2%80%A6]s) 
Mais cela ne remonte pas dans la BAN qui garde l'ancien fichier de janvier, dénommé autrement.
https://adresse.data.gouv.fr/commune/90010

**Comment by IGNFBourcier** [comment]
Api-depot non à jour egalement.
cette bal est moissonée. Mais l'api depot n'est pas mis à jour
La source semble avoir changé c'est peut etre la source du blocage.

**Comment by IGNFBourcier** [comment]
synchro ok
