### ISSUE TITLE
[BanID] Spécification du champ UID de la BAL 1.3 et ajout des champs de la BAL 1.4

### ISSUE THREAD

**Issue by antoineludeau** [BaseAdresseNationale/ban-plateforme#184]
Spécifier la syntaxe utilisé sur le champs UID_Adresse du Format BAL

**Comment by nkokla** [comment]
Test l'implémentation avec la spec suivante : 

@D: > District (UID Commune)
@A: > Address (UID Adresse)
@M: > MainTopo (UID Voie)
@T: > Topo (UID Lieux-dit)

**Comment by FrederiqWilliams** [comment]
J’enlèverai la 3e partie (@t). Le Topo facultatif est au niveau au-dessus il n'apportera pas de valeur supplémentaire à l'identifiant

**Comment by mmortier** [comment]
La partie topo c'est pour gérer le cas où on a deux lieux dits qui ont le même nom sur une commune.
Ca peut arriver après une fusion de commune, préciser l'id du toponyme secondaire doit lever l'ambiguité

**Comment by mmortier** [comment]
Pour les personnes intéressées discussion en cours sur OSMOSE. https://osmose.numerique.gouv.fr/jcms/209046265_SocialTopic/fr/forme-de-l-identifiant-unique-ban-uuid-v4-vs-nano-id c'est accessible via inscription gratuite

**Comment by mmortier** [comment]
Test l'implémentation avec la spec suivante  pour le format BAL AITF 1.3: 

@ a :  UID Adresse obligatoire
@ v : UID Voie obligatoire
@ c : UID commune

**Comment by mmortier** [comment]
Pour les lignes en 99999 on attend 
@ v : UID Voie obligatoire
@ c : UID commune obligatoire

**Comment by nkokla** [comment]
Done : https://github.com/BaseAdresseNationale/ban-plateforme/wiki/DRAFT-%23-Impl%C3%A9mentation-des-BanID
