### ISSUE TITLE
Ajouter la date de publication et de dernière modification d'une BAL

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/ban-plateforme#20]
Discussion sur data.gouv.fr : https://www.data.gouv.fr/fr/datasets/etat-de-la-base-adresse-nationale-par-commune/#discussion-606c03f219b2a88a9f6b05f5

Titre du message: Ajout de colonne date de publication / date de dernière modification ?

Texte du message :

```
Bonjour,

Nous souhaitons valoriser le jeux de données, en montrant la dynamique de publication des BAL sur notre territoire (la région BFC). Est-il possible d'ajouter ces deux champs dans la ressource ?

D'avance Merci,
```

**Comment by jdesboeufs** [comment]
Première analyse, nous n'avons pas conservé de façon fiable la date de première intégration des BAL antérieurement à la mise en place de l'API de dépôt.
Il va falloir reconstituer la donnée à partir des livraisons BAN qui elles sont historisées depuis toujours.

**Comment by jerbou** [comment]
Bonjour, 

Une petit relance sur le sujet. 
Compris la remarque, mais est-ce que la dernière date de modification peut être disponible ?
D'avance Merci,

**Comment by jerbou** [comment]
Bonjour,

Nos financeurs et l'ANCT nous demande des informations sur les BAL publiées sur le territoire BFC en lien avec les actions d'animation.
J'ai constaté un changement dans la structure dans le fichier (champ additionnel composed_at) mais qui n'apporte que peu de vraisemblance (deux dates différentes pour tout le fichier soit 2022-07-01 soit 2022-07-4).

Serait il possible de confirmer (ou refuter) si l'information date de publication des BAL sera rapidement incluse ou non dans le fichier mise à disposition sur 
https://www.data.gouv.fr/fr/datasets/etat-de-la-base-adresse-nationale-par-commune/

D'avance Merci pour la réponse (positive ou négative).

**Comment by LRebours** [comment]
Intéressé par ces champs également

Rem : intéressé également de l'historisation de ce fichier : celle mise en place par Christian Quest ne marche pas : peut-être dû à une exposition non orthodoxe ?
http://files.opendatarchives.fr/data.gouv.fr/adresse-data-gouv-fr/archives/etat-de-la-base-adresse-nationale-par-commune/

**Comment by lvinsonneau** [comment]
Bonjour,
Intéressée également, le besoin vient aussi et surtout du fait que si on regarde le descriptif des fichiers, on peut légitimement penser que la donnée n'a pas été mise à jour depuis 2021 : 
![image](https://user-images.githubusercontent.com/2498403/209940542-e27a1971-1630-40b3-8044-9ed7866543e7.png)

Peut-être peut-on lever le doute de façon plus simple ?

**Comment by FrederiqWilliams** [comment]
Bonjour, 

L'ambiguïté sur la date d'actualité du jeu de données vient du fait que les ressources mentionnées sont distantes. Elles font référence à un autre site internet (en l'occurrence [plateforme.adresse.data.gouv.fr](http://plateforme.adresse.data.gouv.fr/) ce qui ne permet pas à l'heure actuelle d'identifier les évolutions automatiquement. 

L'équipe data.gouv.fr travaille sur un système de crawler qui irait checker régulièrement si une ressource a été modifiée. Nous pouvons espérer la mise en production de ce crawler d’ici quelques semaines. Cela devrait  régler le problème.

**Comment by lvinsonneau** [comment]
Merci @FrederiqWilliams de votre retour !

**Comment by FrederiqWilliams** [comment]
![image](https://github.com/user-attachments/assets/30afdb5b-75e8-41ec-95d5-25203c662a79)

Résolu avec la mise en place du crawler
