### ISSUE TITLE
Erreur en sortie du format CSV

### ISSUE THREAD

**Issue by vdct** [BaseAdresseNationale/ban-plateforme#23]
Bonjour,
sur la livraison BAN CSV du 1er juin je rencontre un souci de manipulation (pour un chargement Postgres en l'occurence) du fait de doubles quotes encadrant un point-virgule sur 2 des lignes du fichier du [Finistère](https://adresse.data.gouv.fr/data/ban/adresses-odbl/latest/csv/adresses-29.csv.gz) :

`29184_b289_00115;29184_B289;115;;"Ty Guen;";29420;29184;Plouénan;;;185663.54;6858070.44;-3.986966;48.617894;entrée;;;PLOUENAN;TY GUEN ;commune;commune;1;`
`29184_b289_00355;29184_B289;355;;"Ty Guen;";29420;29184;Plouénan;;;185468.04;6858001.29;-3.989525;48.617119;entrée;;;PLOUENAN;TY GUEN ;commune;commune;1;
`
merci

**Comment by mmortier** [comment]
Après enquête, les données viennent d'un assemblage qui contient des données du Guichet Adresse Mairie. L'orthographe de "Ty Guen;" est celle qui a été donnée dans le projet d'adressage. Il ne s'agit pas d'un bug mais d'un problème sur les voies qui ont été sans doute mal renommées par l'opérateur. J'ai pu constater également des noms de voies avec des "."
