### ISSUE TITLE
Etude BetaGouv - DataPass

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-plateforme#231]

**Comment by mmortier** [comment]
réunion le 27 juillet 2023 pour avoir une présentation de Datapass.
Peut être intéressant pour mettre en place des autorisations pour les signalements. 
A réétudier en Septembre / Octobre.

**Comment by nkokla** [comment]
Non pertinent pour notre usage. 
A voir pour les signalements : Possibilité de générer les demandes de token pour les pro.
