### ISSUE TITLE
[ID-Fix/Ban-Plateforme] : Mécanisme pour ne pas modifier des entités qui n'ont pas de modification de données. (usage de MD5)

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-plateforme#267]
Utilise une clef md5 sur les attributs relatifs au numero et une clef md5 relative à la voie.
La stocker dans la BAN.
Si la clef est modifié alors procéder à l'update.
SI la clef est identique il ne s'agit pas d'une modification

**Comment by antoineludeau** [comment]
PR sur Id-fix à valider : https://github.com/BaseAdresseNationale/id-fix/pull/70
