### ISSUE TITLE
Problème d'encodage de texte - Sortie JSON pour Addok

### ISSUE THREAD

**Issue by frodrigo** [BaseAdresseNationale/ban-plateforme#336]
Je ne suis pas sûr de reporter le problème au bon endroit.

Dans les données JSON pour Addok il y a du texte mal encodé. Je suppose que le problème d'encodage vient de quelque part plus en amont.

Extrait de données mal encodées
```json
{"id":"71347_ygg0ug","banId":null,"name":"la Croix d'C\ttevoux"}
{"id":"71347_9ukwgt","banId":null,"name":"Lieu Dit la MoussiC)re"}
{"id":"71347_ayj860","banId":null,"name":"Route dC)partementale 984"}
```

**Comment by mmortier** [comment]
Bonjour, après avoir téléchargé le fichier en entrée de la BAN 
https://plateforme-bal.adresse.data.gouv.fr/api-depot/communes/71347/current-revision/files/bal/download

le problème vient de la donnée en entrée de la BAN et non de l'export.
Je clos l'issue, le problème vient des données en entrée. 
Il ne s'agit pas d'un bug.

**Comment by mmortier** [comment]
Il faut s'adresser à la mairie de la commune pour qu'elle puisse corriger ses données.

**Comment by frodrigo** [comment]
Je suis bien d'accord qu'il faut demander à la mairie de corriger les données.

Mais il faut également faire en sorte que ça n'arrive pas à nouveau et ailleurs.

Le sens de ma demande était de faire en sorte que des données invalides n’entrent pas dans la chaîne de traitement.

**Comment by mmortier** [comment]
Oui je comprends. Dans ce cas, l'issue est à adresser au repository https://github.com/BaseAdresseNationale/validateur-bal
