### ISSUE TITLE
[Ban-Plateforme][Amélioration Env Dev] : Envoi d'une BAL locale vers le legacy

### ISSUE THREAD

**Issue by antoineludeau** [BaseAdresseNationale/ban-plateforme#346]
Pourvoir envoyer une BAL facilement dans le système legacy.
Deux étapes de développement : 
- 1 - Mock de l'API de dépôt sur id-fix.
- 2 - Proxification d'id-fix pour permettre à la BAN de ne plus faire de call direct à l'API de dépôt (mais de faire les call à id-fix qui fera lui appel à l'API de dépôt).

**Comment by antoineludeau** [comment]
Partie 1 : DONE
Partie 2 : En cours (@nkokla)

**Comment by vinsag** [comment]
Abandon
