### ISSUE TITLE
Tuiles vectorielles Max Level 14

### ISSUE THREAD

**Issue by Crapaud04** [BaseAdresseNationale/ban-plateforme#39]
Bonjour, 
J’ai essayé le service de Tuiles vectorielles et j'ai eu 2 problèmes.

Le premier c'est qu’il n'y a pas de style par défaut et QGIS nous met un warning au moment d'ajouter la couche.

Le second c'est que je n'ai pas de données en dessus du level 14. (Level 15-16-17-18-19-20 etc.) Celles-ci vont arriver ?

**Comment by jdesboeufs** [comment]
Les zooms supérieurs n'ont aucun intérêt puisque la totalité des points sont déjà présents dans le niveau de zoom maximum proposé. Ce sont des tuiles vectorielles, l'overzoom est de rigueur.
Quand au style c'est à vous de le définir.

**Comment by mmortier** [comment]
AU vu des commentaires je clos le ticket
