### ISSUE TITLE
Des données d'assemblage débordent sur l'emprise d'une BAL

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/ban-plateforme#423]
Exemple : les données d'assemblage de la commune voisine vienne "polluer" l’affichage de la BAL de Niedermorschwihr   https://adresse.data.gouv.fr/base-adresse-nationale/68237_0100#15.61/48.101253/7.236892

Le buffer en contour de commune a été mis en place pour pallier aux cas :
 - ou la précision des contours administratifs ne suffit pas 
 - et pour permettre le positionnement sur le territoire limitrophe dans certains cas ou c'est légitime.

Proposition de réduire ce buffer **sur les zones d'assemblage** pour résoudre ces débordements parasites. 
seuil : à 50 m pour les données ftth? 
(vérifier que ça résoud le problème remonté)

**Comment by vinsag** [comment]
On passe la modification et on fait un yarn compose
