### ISSUE TITLE
Pas de codes postaux lors de l'interrogation de l'API (ou du site) pour la Nouvelle-Calédonie?

### ISSUE THREAD

**Issue by e-dot** [BaseAdresseNationale/ban-plateforme#467]
Lorsqu'on interroge le site ou l'API de la base d'adresse pour une adresse en Nouvelle-Calédonie, le code postal n'est pas retourné.

Exemple adresse à Nouméa "2 Rue du Docteur GUEGAN":
` curl "https://api-adresse.data.gouv.fr/search/?q=2+Rue+du+Docteur+GUEGAN&lat=%2D22%2E275800&lon=166%2E458000&limit=1"`
```json
{"type":"FeatureCollection","version":"draft","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[166.444479,-22.273405]},"properties":{"label":"2 Rue du Docteur GUEGAN Nouméa","score":0.9739190584893359,"housenumber":"2","id":"98818_zpfhbu_00002","name":"2 Rue du Docteur GUEGAN","citycode":"98818","x":445808.63,"y":214303.12,"city":"Nouméa","context":"988, Nouvelle-Calédonie","type":"housenumber","importance":0.68783,"street":"Rue du Docteur GUEGAN","distance":1415}}],"attribution":"BAN","licence":"ETALAB-2.0","query":"2 Rue du Docteur GUEGAN","center":[166.458,-22.2758],"limit":1}
```

La réponse **ne contient pas le code postal** dans l'attribut `label` ("2 Rue du Docteur GUEGAN Nouméa"), ni aucun attribut `postcode`.

A l'inverse, lorsqu'on interroge la base d'adresse pour une adresse en métropole, l'information du code postal est bien retournée.

Exemple adresse à Paris "21 Avenue de Ségur" :
`curl "https://api-adresse.data.gouv.fr/search/?q=21+Avenue+de+SEGUR&lat=48.855991&lon=2.3469720&limit=1"`
```json
{"type":"FeatureCollection","version":"draft","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[2.310462,48.851808]},"properties":{"label":"21 Avenue de Ségur 75007 Paris","score":0.9737922738684734,"housenumber":"21","id":"75107_8909_00021","name":"21 Avenue de Ségur","postcode":"75007","citycode":"75107","x":649402.01,"y":6861528.37,"city":"Paris","district":"Paris 7e Arrondissement","context":"75, Paris, Île-de-France","type":"housenumber","importance":0.68844,"street":"Avenue de Ségur","distance":2709}}],"attribution":"BAN","licence":"ETALAB-2.0","query":"21 Avenue de SEGUR","center":[2.346972,48.855991],"limit":1}
```

Comment peut-on améliorer cela? Est-ce un problème de données dans la base de référence?

E.

**Comment by FrederiqWilliams** [comment]
Conclusions : les données de DATANOVA mentionnent plusieurs codes postaux.  La Poste ne dispose pas des emprises. 
Prise de contact avec NC OK. 
Vont générer les BAL au format 1.4 pour intégrer le nouveau socle technique. 

--> il faudra gérer une actualisation spécifique des fichiers DATANOVA, ainsi qu'un couche spécifique des contours postaux pour la NC. 
Dans un premier temps, pour générer  rapidement les CP sur les 6 BAL de NC : 

Acutaliser Datanova_extNC sur : 
    - KAALA GOMEN - code postal domicile : 98817
    - KONE - code postal domicile : 98859
    - MONT DORE - code postal domicile : 98809
    - NOUMEA - code postal domicile : 98800
    - POUEMBOUT - code postal domicile : 98825
    
- DUMBEA -  2 codes postaux, 98835 et 98800, : récupérer les contours, créer une couche spécifique contours postaux_NC
 
Pour toutes les autres communes : on actualisera  DATANOVA_ extensionNC et les contours_NC au fur et à mesure de la publication des BAL
