### ISSUE TITLE
Ajouter à la white-list la commune de Segré-en-Anjou Bleu (code INSEE 49331)

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/ban-plateforme#468]
Ajouter à la white-list la commune de Segré-en-Anjou Bleu pour bénéficier du certificat d'adressage 
la commune a généré ses id 1.4

Code INSEE 49331

**Comment by vinsag** [comment]
Traité via un ticket sur id-fix, mis en production je ferme le ticket
