### ISSUE TITLE
[Certif] Ajouter 10 communes dans la white-list + ajout du certificat

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/ban-plateforme#487]
Ajouter dans la white-list du nouveau socle les 10 communes suivantes, qui souhaitent bénéficier du certificat d'adressage. 
(idban +certification + parcelles ok)
Puis activer la fonctionnalité "Certificat" sur ces communes

Avène | 34019
Val-du-Faby | 11131
CÉBAZAN | 34070
DELETTES | 62265
BARBIERES | 26023
OUDON | 44115
Bidart | 64125
Chuzelles | 38110
Villars-sur-Var | 06158
Beaulieu sur Layon | 49022

**Comment by antoineludeau** [comment]
Deux communes n'ont pas encore d'identifiants : Villars-sur-Var (06158) et Beaulieu sur Layon (49022)

**Comment by FrederiqWilliams** [comment]
ok merci je vais les prévenir
