### ISSUE TITLE
Adapter les scripts pour la récupération Codes Postaux à partir des nouveaux fichiers DGFIP

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/ban-plateforme#49]
Les fichiers FANTOIR et FIMOCT évoluent en février 2023. 
FANTOIR devient TOPO
Les codes postaux seront dans le nouveau fichier "ACHEMINEMENT"

Il faut adapter les scripts en place pour suivre cette évolution. 
(demande à DGFIP d'échantillons des nouveaux fichiers)

**Comment by antoineludeau** [comment]
Première version de code réalisée à partir du fichier test envoyé avec les spécifications du fichier ACHEMINEMENT de la DGFiP (https://github.com/BaseAdresseNationale/codes-postaux/tree/test/antoineludeau/nouveau-format-fichier-source-acheminement).

En attente des informations de la DGFiP sur un premier fichier de production (endroit où il sera stocké ? même format que le fichier test ? etc...)

**Comment by mmortier** [comment]
les fichiers de juillet 2023 : https://www.data.gouv.fr/fr/datasets/fichier-des-donnees-acheminement/

**Comment by mmortier** [comment]
Un nouveau processus est sur le point d'être mis en production.
