### ISSUE TITLE
[Exports Addok] Les codes postaux de Nouvelle-Calédonie ne remontent pas dans l'API

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/ban-plateforme#492]
remontée support : 
Nous remarquons que vous n'envoyez pas le code postal (champ "postcode") dans les adresses en Nouvelle-Calédonie.
le code postal est bien renvoyé en Métropole, mais pas en Nouvelle-Calédonie.
Pourtant, les données existent car le site national de l'adresse affiche bien : « Code postal : 98800 ».
https://adresse.data.gouv.fr/base-adresse-nationale/98818_w65mkd_00011#19/

**Comment by IGNFBourcier** [comment]
https://api-adresse.data.gouv.fr/search/?q=11%20Avenue%20James%20Cook%2098800%20Noum%C3%A9a&type=housenumber&autocomplete=1
renvoie bien le champ postcode. (donnée du 21/11/2024). 
Les 6 communes de nouvelle-calédonie ayant une bal sont présentes sur le nouveau socle et présentent le champs postcode dans les exports. (du 27/11/2024)
Remontée anterieur au 21/11/2024 ?

**Comment by FrederiqWilliams** [comment]
Oui le signalement date du 14/11. 
OK résolu, merci Florent
