### ISSUE TITLE
Mise à jour 2023 des communes

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/ban-plateforme#50]
Besoin :  mise en conformité de la structure administrative de la BAN avec les évolutions annuelles des modifications sur les communes (fusions et modifications des noms)
Intégrer le COG de l'INSEE qui sera publié le 17 fevrier 2023. 

![image_INSEE_2023](https://user-images.githubusercontent.com/97727151/212680605-3d65906b-44cc-4343-94c6-e579d765d099.png)

![image_INSEE_2023_2](https://user-images.githubusercontent.com/97727151/212680618-65f07a4a-fae0-42b8-a527-812090f0a497.png)

**Comment by mmortier** [comment]
Suite à la mise à jour du COG, on a relancé le yarn compose. C'est bon maintenant.
