### ISSUE TITLE
Documenter le schema des données BAN

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-plateforme#55]
Dans le cadre des Adresse_Lab il y a un sujet sur les exports BAN avec un format enrichi.
La BAN exporte avec un format CSV historique, un format BAL.

Le format BAN n'est pas encore standardisé, il doit être documenté à l'instar du schéma BAL.

Le Schéma BAN cible est un format BAL qui peut être enrichi de certaines informations (cet enrichissement potentiel est à discuté en Adresse_Lab).
Produire un schéma BAL (+ les potentiels ajouts).

**Comment by FrederiqWilliams** [comment]
Ticket à considérer au regard du travail de standardisation qui est lancé en 2023. Je suggère  de dissocier les deux actions avec des tickets spécifiques : 
- documenter le schéma --> prévu dans le cadre du travail de standardisation
- définir le nouveau format d'export BAN = BAL enrichi

**Comment by nkokla** [comment]
On vient de créer une tache en draft pour la définition du format d'export des données BAN. 
Cette _issue_ ci est donc dédié a la documentation du schéma de la Base.
