### ISSUE TITLE
investigation code Fantoir modifié sans raison lors de l'intégration dans la BAN

### ISSUE THREAD

**Issue by FrederiqWilliams** [BaseAdresseNationale/ban-plateforme#66]
Bug remonté par Metz Métropole : 

"Dans l’exemple de la Sente à My à Metz, la DCM date de 1988, il ne s’agit donc pas d’une rue nommée ou renommée récemment.
Son RIVOLI est disponible ici https://www.data.gouv.fr/fr/datasets/fichier-fantoir-des-voies-et-lieux-dits/:
5704636400HRUE SENTE A MY

C’est bien celui qu’on a dans notre base de donnée, et on le retrouve dans la clé interop que l’on publie dans la BAL de Metz :
57463_6400_00072

Et au final dans la BAN il devient :
57463_09b5rs_00072 "

**Comment by mmortier** [comment]
Le code fantoir n'est pas retrouvé dans le code actuel car pour retrouver un candidat correspondant aux données DGFIP (données fantoir) nous devons avoir les mêmes mots signifiants hors ici : 

- les mots signifiants dans la BAN :  significantWordsString: 'sente my'
- les mots signifiants dans les données fantoir : significantWordsString: 'rue sente my'

Sans une égalité stricte la correspondance n'est pas trouvé dans le code cf repository fantoir dans lib > index.js 
```
// SIGNIFICANT WORDS
    const significantWordsCompareResults = scopedFantoir.filter(fantoirItem => {
      return fantoirItem.libelleStringContexts.some(lsc => {
        return **lsc.significantWordsString === ctx.significantWordsString**
      })
    })
```

C'est dommage d'avoir un tel comportement pour un mot signifiant rue... Néanmoins de corriger ce processus peut avoir des effets de bord. Par exemple si on enlève dans les mots signifiants tous les mots rue, voie, avenue... on pourrait attribuer de mauvais code fantoir s'il existe une rue sente a my et une avenue sente a my...

Je ne peux donc corriger ce soucis dans en créer un autre. Il faudrait que les données DGFIP correspondent aux données BAN.

D'ici la fin de l'année l'identifiant unique de l'adresse devrait permettre d'associer une clef unique à chaque adresse et voie dans la BAN lorsque la commune dispose de sa BAL. Si l'on prend en référence ce nouvel ID celui-ci sera stable.
