### ISSUE TITLE
Automatisation de la génération & publication des fichiers BAN

### ISSUE THREAD

**Issue by antoineludeau** [BaseAdresseNationale/ban-plateforme#73]
Automatisation du lancement des scripts qui est aujourd'hui réalisé manuellement : 
- "build-dist.sh"
- "publish.sh"

**Comment by mmortier** [comment]
# calcul des exports des données de la BAN tous les jours sauf le week end à 1h du matin heure machine
0 1 * * 1-5 cd /srv/pm2-apps/ban-plateforme && ./build-dist.sh >> /srv/pm2-apps/ban-plateforme/build-test.log
# publication des exports des données 1h après le build
0 2 * * 1-5 cd /srv/pm2-apps/ban-plateforme && ./publish.sh >> /srv/pm2-apps/ban-plateforme/publish-test.log


Mise en place le 14 mars. A vérifier demain matin

**Comment by mmortier** [comment]
doublon avec ticket infra https://github.com/BaseAdresseNationale/infra/issues/4

**Comment by mmortier** [comment]
Pour les exports CSV et CSV bal ça fonctionne mais pas pour addok.. Le fichier addok-bundle-france n'est pas complet

**Comment by mmortier** [comment]
Correction du script de generation du bundle addok en mettant des chemins absolu. Le problème de corruption du bundle est corrigé ce matin après lancement du nouveau script via le cron.
