### ISSUE TITLE
adresses-22.csv : ligne tronquée

### ISSUE THREAD

**Issue by vdct** [BaseAdresseNationale/ban-plateforme#76]
Bonjour,
dans le fichier https://adresse.data.gouv.fr/data/ban/adresses-odbl/latest/csv/adresses-22.csv.gz disponible ce matin une ligne est tronquée, pour l'adresse "3 c Rue du Martinet" à Lamballe-Armor. Les colonnes id,id_fantoir et numero sont absentes, la ligne commence avec la colonne "rep".
merci

**Comment by mmortier** [comment]
Il y a surement eu un problème lors de la génération des exports.
Dans le fichier d'aujourd'hui il n'y a plus de problème.
Je clos le ticket

**Comment by vdct** [comment]
La dernière version de mon côté est du 22/3 et le problème n'y était plus en effet. Merci
